### ISSUE TITLE
$X earned $JOY = Automatic Founding Member Status?

### ISSUE THREAD

**Issue by mrexpat** [Joystream/marketing#201] opened 2022-03-08 11:47 UTC
## Background

I expressed my thoughts about the requirement to obtain Founding Member status in order to unlock any earned $JOY allocation to Bedeho and Ben. In short, I think only allowing people to receive their earned $JOY by becoming a FM is a little like trying to get married on the first date.

We are asking for a big commitment. We're saying unless you're willing to commit to XYZ to become a FM, you won't receive the rewards you earn. Of course a big issue here was also the elusive prospect of actually becoming a FM which has been unclear, but that should be easier going forward. All in all, I'm quite certain this big commitment ask is preventing people from even getting started.

With that said, my point was effectively to question the requirement of becoming FM altogether. Why not release any $JOY earned regardless of FM status. I mean.. if they earned the $JOY, then they presumably did contribute some value to the project, or they would not have earned the $JOY in the first place.

If our objective is to get as many high-value contributors as possible, my argument was that dropping the FM requirement would help facilitate that. Now, it would also mean we would be giving out $JOY allocation to people who are not there for the long term, but the upside would be more people getting involved, and more people getting increasingly excited and committed to the project (this was my point about getting married on the first date--that's not how we operate as humans.. we start small, and then we escalate our commitment to things over time).

## Status

@bedeho could also see the issue, and is not super concerned about any governance issues stemming from a lot of low-value contributors having $JOY tokens and voting rights.

We decided a good option may be somewhere in the middle of where we are now, and a full abandoning of the FM status requirement to unlock $JOY rewards. If this is ineffective we may consider dropping the requirement.

Instead we thought about defining an actual $JOY amount needed to become FM.

For example: "If you earn $2,000 worth of $JOY - you will be granted FM status".

1) It makes it very clear what exactly needs to be done
2) This number, which I am hoping to get some ideas on in this issue, should potentially be a little lower than what it would have been historically, in order to combat the "marriage on the first date"-level commitment we're asking for

So..

Thoughts on this? Thoughts on what the number could be? You could think about it in terms of "5 average bounties", or "2 council terms as a WG worker".. or something along those lines, to come up with a number

@mochet
@bedeho
@blrhc 
@bwhm

**Comment by adovrodion** [comment] 2022-03-09 06:28
I think that if you do that, you should put the minimum amount - $6,000 (to skip only nodrunners). And the minimum requirement to add - to be several times an active consul and perform at least 2 KPI (to be marked as active)

**Comment by blrhc** [comment] 2022-03-09 10:50
`if they earned the $JOY, then they presumably did contribute some value to the project, or they would not have earned the $JOY in the first place`
I would invite you to look at the places (t)JOY is currently or has previously been being earned on the testnet. It's quite evident that in many cases, the "market" is very inefficient at setting appropriate rewards for things. We have had bounties pay out silly amounts for extremely low-quality contributions etc.

On the whole the tJOY rewards do correlate with quality of contributions, but when this is the case, people get inducted anyway, and I make it clear to them along the way that they are making good progress towards achieving the FM status.

It seems to me that the only people this policy will help are:
(a) Sybil attackers in their various forms (referral program, faucet abusers etc.)
(b) People who relentlessly target poorly designed and optimised bounties (e.g. CC-BY uploads every week)
(c) Node runners/validators, who contribute nothing to the governance side of things
(d) _Probably more "bad" people I haven't considered_

Which one is going to create better contributors?
(i) We will look at your contributions holistically to determine whether you're a valuable long-term contributor
(ii) Race to collect JOY! Once you reach threshold, free money $$$$ ambassador JoYstreaM

Of course, if the testnet gets more participation and oversight and somehow becomes a lot more of an efficient market for JOY allocations in that sense, then your argument is a lot stronger than mine. However, mine is based on my view that there's little evidence that such an environment will emerge any time soon, even though Incentives 3.0 is very much focused on this.

Maybe there's no harm in trying it, I just want to make my views on the subject as clear as possible.

##### Side Note 
`"If you earn $2,000 worth of $JOY - you will be granted FM status".`
WTF, I have to earn $2,000 worth of JOY???
that sounds like a crazy amount of effort, and if I don't get to that milestone, I lose real money :((

vs `Make contributions to the platform`
Oh cool dawg, I can help build a DAOOO! I guess if I do my best to improve this thing, the project maintainers will notice my enthusiasm and I can join the inner circle of the guys and gals building this thing. Nice! #community

**Comment by mochet** [comment] 2022-03-12 15:25
I think setting a figure like this sets a dangerous precedent because you're effectively removing all control safeguards and leaving things entirely up to the DAO governance. Once you do this, you can't take it back.

There may be some alternatives though:
- FM status can be obtained via `text proposal` (having to be done on 2 different councils) -- there is a cost associated with doing a proposal too. Given the much higher cost of governance coming soon, this will make approval a lot more difficult.
 
- Doing jobs etc adds some form of certification to a user profile--so if they do enough different jobs then they can basically guarantee that they've "learned enough" (this is harder to manage)

**Comment by bedeho** [comment] 2022-03-12 15:34
> safeguards and leaving things entirely up to the DAO governance

This is not very specific, leaving aside abuse (which is by design discretionary), what exactly is it you are saying DAO governance risks resulting in, which is bad, with this scheme?

I did not really understand your what problem your alternatives solve. Doing jobs is by def. almost going to be a requirement here, perhaps with the exception of referrals, but not sure how many verified people you would need to get to reach our prospribed FM limit, as it depends on value of each referral, and limit. But lets say you refer 12 people, all at 500USD a pop in $JOY, which puts you exactly at 6K AND all of those 12 people are not Sybills and they get verified (which means they must have done at least a few hundred bucks, if not more, worth of work). That seems like a decent amount of work, is this bad? and this seems like the most borderline case.

**Comment by mochet** [comment] 2022-03-12 15:42
> This is not very specific, leaving aside abuse (which is by design discretionary), what exactly is it you are saying DAO governance risks resulting in, which is bad, with this scheme?

A group of people could overtake the entire council repeatedly, send out tons via `spending proposals` or any of the working groups could be taken over.

Even a simple typo could result in someone getting massive rewards unintentionally: https://github.com/Joystream/joystream/issues/2426

A single WG with a sufficient budget and a bad actor as its lead could basically make someone an FM in one step.

I presume that anyone doing such an action would be banned from the FM program anyway, but then you start having complex, expensive arguments about the distinction between the person doing the action and the recipient of the action.

I am just very cautious in what is promised to users, and if they are able to manipulate things in a way that isn't foreseen then it can result in a lot of angry people who are very difficult to deal with. This isn't a promise that can be adjusted once it is made, which is why I am cynical about it.

I do really see the benefit in having this though, it makes the FM program have a lot more promise for users compared to before, my only concern is that it can't easily be adjusted after the fact.

**Comment by bedeho** [comment] 2022-03-12 15:49
> A group of people could overtake the entire council repeatedly, send out tons via spending proposals or any of the working groups could be taken over.

Spending proposals have no value in FM program, also, doing this sort of resource allocation would undemine their own $JOY earning, and lastly, if what they actually was doing was considered abusive, we could still just say: no, in terms of their $JOY allocation rewards, or even kick people out.

> Even a simple typo could result in someone getting massive rewards unintentionally: 

We have discretion to fix that.

> but then you start having complex, expensive arguments about the distinction between the person doing the action and the recipient of the action.

Thats really unavoidable, the same argument simply moves back to "why did X get FM status but not Y".

**Overall: not only do we have retroactive discretion, but we can change forward looking policy at any time, with very limited damage. With that in mind, the substantial upside of removing the ambiguity in the minds of participants, it on balance is worth attempting.**

**Comment by mochet** [comment] 2022-03-12 16:32
> Thats really unavoidable, the same argument simply moves back to "why did X get FM status but not Y".

I think this is a lot more complex than that argument because an attack may lump in good users alongside those seeking to attack the system and it would be almost impossible to distinguish them.

I do like the idea of having this, but I think it needs to be approached from what influence a single bad actor or multiple bad actors could have.

I suppose the core question is:
- How much `JOY` could a bad actor, in one step assign? Particularly if they were to assign this value to multiple parties?

As long as that question is built in to whatever the amount is, then it would be better.

**Comment by bedeho** [comment] 2022-03-12 16:45
> How much JOY could a bad actor, in one step assign? Particularly if they were to assign this value to multiple parties?

I agree, we have to take this into account.

**Closed** 2022-04-07 13:40 UTC
